<p><a href="<?php echo $this->url(
    array(
        'controller' => 'group',
        'action'     => 'new'
    ), 
    'default', 
    true);
    ?>">New Group</a></p>
    <?php
    //var_dump($this->group->find(1));
    $form = $this->group->getForm();
    //$v = new Zend_Validate_Regex('/[A-Za-zΆ-ώ_0-9]+/u');
    //echo $v->isValid('Καποδίστριας') ? 'true' : 'false';
    echo $form;
    //echo $validator->isValid($_POST['group']['groupname']) ? 'true' : 'false';
    if($_POST['group']) {
    	echo $form->isValid($_POST['group']) ? 'true' : 'false';
    	echo var_dump($form->getErrors());   	
    }
    ?>
    <?php if(count($this->paginator)) : ?>
    	<ul>
			<?php foreach ($this->paginator as $item): ?>
  				<li><?php var_dump($item); ?></li>
			<?php endforeach; ?>
		</ul>
    	<?php echo $this->paginator; ?>
    <?php endif;?>